swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - image/svg
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /followers:
    x-swagger-router-controller: twitter
    get:
      description: Returns an array of followers ids
      operationId: followers
      parameters:
        - name: user
          in: query
          description: The screename or userid
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListResponse"
          # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /friends:
    x-swagger-router-controller: twitter
    get:
      description: Returns an array of friends ids
      operationId: friends
      parameters:
        - name: user
          in: query
          description: The screename or userid
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListResponse"
          # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /commonfriends/{user1}/{user2}:
    x-swagger-router-controller: twitter
    get:
      description: get the common friends between two users
      operationId: commonfriends
      parameters:
        - name: user1
          default: itzareyesMX
          in: path
          description: First userid or screen_name for comparisson
          required: true
          type: string
        - name: user2
          default: d5lment
          in: path
          description: Second userid or screen_name for comparisson
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommonFriendsResponse"
          # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /commonfriendsGraph/{user1}/{user2}:
    x-swagger-router-controller: twitter
    get:
      description: get the common friends between two users
      operationId: CommonFriendsGraph
      parameters:
        - name: user1
          default: itzareyesMX
          in: path
          description: First userid or screen_name for comparisson
          required: true
          type: string
        - name: user2
          default: d5lment
          in: path
          description: Second userid or screen_name for comparisson
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommonFriendsGraph"
          # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  CommonFriendsGraph:
    properties:
      message:
        format: string
  CommonFriendsResponse:
    required:
      - user1followers
      - user2followers
      - commonfollowers
    properties:
      user1followers:
        type: array
        items:
          type: number
        format: integer
      user2followers:
        type: array
        items:
          type: number
        format: integer
      commonfollowers:
        type: array
        items:
          type: number
        format: integer
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ListResponse:
    required:
      - users
    properties:
      users:
        type: array
        items:
          type: string
